# RAG System Configuration

# LLM Configuration
llm:
  model: "llama3.2:3b"
  temperature: 0.8
  max_tokens: 500
  base_url: "http://10.0.7.1:11434"

# RAG Configuration
rag:
  similarity_threshold: 0.2
  max_chunks: 3
  chunk_size: 1000
  chunk_overlap: 200

# Vector Database Configuration
vector_db:
  collection_name: "documents"
  
# Document Processing Configuration
document_processing:
  supported_formats:
    - pdf
    - txt
    - md
    - html
  max_file_size_mb: 50

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  cors_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Playwright Configuration
playwright:
  browser:
    height: 800
    width: 1280
    headless: false