apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rag-backend-pdb
  namespace: rag-system
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rag-backend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: reflex-frontend-pdb
  namespace: rag-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reflex-frontend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb
  namespace: rag-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx