apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rag-system-base

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- chromadb.yaml
- redis.yaml
- rag-backend.yaml
- reflex-frontend.yaml
- nginx.yaml

commonLabels:
  app.kubernetes.io/instance: rag-system
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize

images:
- name: rag-system/backend
  newTag: latest
- name: rag-system/reflex
  newTag: latest

# Resource name prefixes
namePrefix: rag-

# Common annotations
commonAnnotations:
  kubernetes.io/managed-by: "kustomize"
  app.kubernetes.io/created-by: "devops-team"